# experiment:
seed: 123
experiment_name: "vae_template_"
alpha: 0.98 # smoothing constant for exponential moving average
log_every_iters: 100
checkpoint_every: 40
validate_every: 1
plot_image_every: 10
num_samples: 200000
num_workers: 1
display_iters: True
display_pbars: True
enable_time_profiling: False

# dataset
shuffle: True
output_dir: "./outputs/at_"
train_size: 0.7
val_size: 0.15
test_size: 0.15
include_text: True

# Embeddings
pretrained_embeddings: None
embed_size: 300

# model:
## rnn
rnn_hidden_dim: 64
concater_output_dim: 32
hidden_dim: 200
num_hidden_layers: 3
z_dim: 20
num_layers: 2
dropout_p: 0.3
model_verbose: True

# train:
# https://stackoverflow.com/questions/30458977/yaml-loads-5e-6-as-string-and-not-a-number
num_epochs: 50
es_criteria: 8
reduce_lr_criteria: 3
es_threshold: 0.005
learning_rate: 1.e-4
batch_size: 128
weight_decay: 0.0001
is_mse_loss: True
