RNG_SEED: 100
TUNE_LR: False
LOG_DEST: "file"
IS_TB_LOG: True
PATHS:
  OUT_DIR: ../experiments
  EXPERIMENT_NAME: cool_experiment
  DATAPATH: ../data/cifar10/
MODEL:
  TYPE: flat
  INPUT_DIM: 315
  NUM_CLASSES: 10
  GRAYSCALE: True
  LOSS_FUN: "cross_entropy"
BN:
  USE_PRECISE_STATS: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 3e-4
  LR_POLICY: exp
  MAX_EPOCH: 5
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
  GRAD_CLIP_T: 1e4
TRAIN:
  DATASET: mnist
  SPLIT: train
  VALID_SIZE: 0.2
  BATCH_SIZE: 128
  EVAL_PERIOD: 1
  ES_PATIENCE: 10
  ES_THRESHOLD: 1e-5
TEST:
  DATASET: mnist
  SPLIT: test
  BATCH_SIZE: 128
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 0
CUDNN:
  BENCHMARK: False